name: Deploy App

on:
  push: 
     branches: [main]

jobs: 
   deploy: 
      runs-on: self-hosted

      env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.event.workflow_run.head_sha }}

      steps: 
        - name: checkout code
          uses: actions/checkout@v4

        - name: setup docker compose
          uses: docker/setup-compose-action@v2
         
        - name: Deploy app
          run: docker compose -d up